### ISSUE TITLE
Code quality analysis for pull requests

### ISSUE THREAD

**Issue by julianolf** [ecanuto/terramorf#3]
It can be helpful to have a tool checking the code for syntax errors or possible pitfalls.

[Shellcheck](https://www.shellcheck.net/) is a great tool for doing exactly that on shell scripts.

Here's an example:
```sh
% shellcheck terramorf

In terramorf line 32:
VERSION=0.5.2
^-----^ SC2034 (warning): VERSION appears unused. Verify use (or export if used externally).

For more information:
  https://www.shellcheck.net/wiki/SC2034 -- VERSION appears unused. Verify us...
```

A GitHub Actions workflow running this tool against pull requests might interest you.

**Comment by ecanuto** [comment]
The commit 4626a2f solves the shellcheck message. Will keep issue opened since will be a good idea to have a workflow for pull requests.
